### ISSUE TITLE
calico node error about MTU

### ISSUE THREAD

**Issue by TaurusM** [kubesphere/kubekey#1572] opened 2022-10-31 11:16 UTC
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.3.0", GitCommit:"4a25a844", GitTreeState:"", GoVersion:"go1.18.7"}

### What is your os environment?

ubuntu20.04.4

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master01, address: 192.168.21.111, internalAddress: 192.168.21.111, password: "ming"}
  - {name: master02, address: 192.168.21.112, internalAddress: 192.168.21.112, password: "ming"}
  - {name: master03, address: 192.168.21.113, internalAddress: 192.168.21.113, password: "ming"}
  - {name: node01, address: 192.168.21.114, internalAddress: 192.168.21.114, password: "ming"}
  - {name: node02, address: 192.168.21.115, internalAddress: 192.168.21.115, password: "ming"}
  - {name: node03, address: 192.168.21.116, internalAddress: 192.168.21.116, password: "ming"}
  roleGroups:
    etcd:
    - master01
    - master02
    - master03
    control-plane:
    - master01
    - master02
    - master03
    worker:
    - node01
    - node02
    - node03
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: 192.168.21.110
    address: "192.168.21.110"
    port: 6443
  kubernetes:
    version: v1.21.14
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: crio
  etcd:
    type: kubekey
  network:
    plugin: calico
    calico:
      ipipMode: Never  # IPIP Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, vxlanMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Always]
      vxlanMode: Always  # VXLAN Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, ipipMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Never]
      vethMTU: 1500  # The maximum transmission unit (MTU) setting determines the largest packet size that can be transmitted through your network. By default, MTU is auto-detected. [Default: 0]
    kubePodsCIDR: 172.16.0.0/16
    kubeServiceCIDR: 10.96.0.0/16
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: 192.168.21.111,192.168.21.112,192.168.21.113
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: LoadBalancer
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    # resources: {}
    jenkinsMemoryLim: 8Gi
    jenkinsMemoryReq: 4Gi
    jenkinsVolumeSize: 8Gi
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:
    enabled: false
    kubeedge:
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  terminal:
    timeout: 600
```

### A clear and concise description of what happend.

```shell
kubectl logs -f -n kube-system calico-node-77wg9
```
```shell
2022-10-31 11:07:21.681 [INFO][66] monitor-addresses/reachaddr.go 47: Auto-detected address by connecting to remote Destination="192.168.21.114" IP=192.168.21.114
2022-10-31 11:07:21.682 [INFO][66] monitor-addresses/autodetection_methods.go 143: Using autodetected IPv4 address 192.168.21.114/24, detected by connecting to 192.168.21.114
2022-10-31 11:07:23.374 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:07:23.375 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:07:26.362 [INFO][57] felix/summary.go 100: Summarising 11 dataplane reconciliation loops over 1m3s: avg=4ms longest=6ms (resync-filter-v4)
2022-10-31 11:07:33.376 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:07:33.376 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:07:43.378 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:07:43.378 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:07:53.382 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:07:53.382 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:08:03.384 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:08:03.384 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:08:13.386 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:08:13.386 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:08:14.504 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="node01"
2022-10-31 11:08:14.504 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="node01"
2022-10-31 11:08:21.683 [INFO][66] monitor-addresses/reachaddr.go 47: Auto-detected address by connecting to remote Destination="192.168.21.114" IP=192.168.21.114
2022-10-31 11:08:21.684 [INFO][66] monitor-addresses/autodetection_methods.go 143: Using autodetected IPv4 address 192.168.21.114/24, detected by connecting to 192.168.21.114
2022-10-31 11:08:23.388 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:08:23.389 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:08:28.289 [INFO][57] felix/summary.go 100: Summarising 10 dataplane reconciliation loops over 1m1.9s: avg=5ms longest=13ms ()
2022-10-31 11:08:33.391 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:08:33.391 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:08:43.394 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:08:43.394 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:08:53.397 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:08:53.397 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:09:03.399 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:09:03.399 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:09:13.402 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:09:13.402 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:09:14.582 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="node03"
2022-10-31 11:09:14.582 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="node03"
2022-10-31 11:09:21.685 [INFO][66] monitor-addresses/reachaddr.go 47: Auto-detected address by connecting to remote Destination="192.168.21.114" IP=192.168.21.114
2022-10-31 11:09:21.686 [INFO][66] monitor-addresses/autodetection_methods.go 143: Using autodetected IPv4 address 192.168.21.114/24, detected by connecting to 192.168.21.114
2022-10-31 11:09:23.404 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:09:23.404 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:09:24.594 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="master01"
2022-10-31 11:09:24.594 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="master01"
2022-10-31 11:09:28.602 [INFO][57] felix/summary.go 100: Summarising 8 dataplane reconciliation loops over 1m0.3s: avg=5ms longest=12ms ()
2022-10-31 11:09:33.408 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:09:33.408 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:09:34.605 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="master03"
2022-10-31 11:09:34.606 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="master03"
2022-10-31 11:09:34.612 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="master02"
2022-10-31 11:09:34.612 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="master02"
2022-10-31 11:09:43.410 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:09:43.410 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:09:44.613 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="node02"
2022-10-31 11:09:44.613 [INFO][57] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="node02"
2022-10-31 11:09:53.413 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:09:53.413 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:10:03.416 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:10:03.416 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
2022-10-31 11:10:13.418 [INFO][57] felix/vxlan_mgr.go 679: VXLAN device MTU needs to be updated device="vxlan.calico" ipVersion=0x4 new=1500 old=1450
2022-10-31 11:10:13.418 [WARNING][57] felix/vxlan_mgr.go 681: Failed to set vxlan tunnel device MTU error=invalid argument ipVersion=0x4
```
```shell
ip addr
```
```shell
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:2f:ca:7f brd ff:ff:ff:ff:ff:ff
    inet 192.168.21.114/24 brd 192.168.21.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe2f:ca7f/64 scope link
       valid_lft forever preferred_lft forever
4: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 8e:94:9e:56:ba:ab brd ff:ff:ff:ff:ff:ff
    inet 10.96.0.3/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.70.72/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.243.55/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.18.13/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.34.2/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.220.117/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.216.139/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.177.146/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.139.115/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.176.7/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.3.157/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.31.39/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.158.133/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
5: cni0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 82:00:cc:30:5d:52 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/16 brd 172.16.255.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 1100:200::1/24 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::8000:ccff:fe30:5d52/64 scope link
       valid_lft forever preferred_lft forever
9: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 66:aa:99:2f:dc:24 brd ff:ff:ff:ff:ff:ff
    inet 172.16.220.0/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::64aa:99ff:fe2f:dc24/64 scope link
       valid_lft forever preferred_lft forever
10: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 22:f5:f4:d5:b6:d4 brd ff:ff:ff:ff:ff:ff
    inet 169.254.25.10/32 brd 169.254.25.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
11: cali0532837e9b7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 6b3e3454-1da5-4cbb-9491-7962fb683abe
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
14: calida548b3a2d0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 26b87be4-2dc0-4290-a1a1-b539fba8d603
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
15: califc1a1c0283b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 5aaad7f8-dcbe-497e-9e68-b8c89f382a23
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
16: calif7c7bbacc1d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns daf0258e-2744-4c11-a13e-d8a071dc9d83
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
17: cali65d3689e6a0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 0b1e2897-c4fc-45bb-9a4d-aa88e858a5d1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
18: cali8b24c3dbe64@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 7456aea4-05bd-409c-9dd3-9ad12bcc512e
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
19: calife02372d33f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns b8085053-78fb-4288-a7a9-fe988d4113b8
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
21: calib359061c5c7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 31066b71-a659-4c8a-a554-3ae423c12dde
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
```

### Relevant log output

```shell
showed above
```

**Comment by 24sama** [comment] 2022-11-01 08:17
Can you try to unset the `vethMTU`? The value will be auto-detection by the calico itself.

**Comment by TaurusM** [comment] 2022-11-01 09:20
It's OK, when I unset the `vethMTU` key-value. 
This problem only occur with set `vethMTU`.

**Comment by 24sama** [comment] 2022-11-02 06:01
So, it looks like caused by setting the wrong value. I will close this issue, if you have any new information feel free to reopen it.

**Closed by 24sama** 2022-11-02 06:01 UTC
Labels: bug
